/* 
	This file is automatically generated by the add_madgraph_proc.py interface 
	Don't touch this file unless you know exactly what you're doing.
*/

#include <string>
#include "Reweightor.h"
#include "Global.h"

Matrixelements * Reweightor::getMatrixElements(){

	// if(procName == "pp2sqgo"){
	// 	Global::print("Reweightor","Use Matrixelements_pp2sqgo for Matrixelement Reweighting.");
	// 	return new Matrixelements_pp2sqgo();
	// }
	// if(procName == "pp2sqsqbar"){
	// 	Global::print("Reweightor","Use Matrixelements_pp2sqsqbar for Matrixelement Reweighting.");
	// 	return new Matrixelements_pp2sqsqbar();
	// }
	if(procName == "pp2sqsqbar_nogluino"){
		Global::print("Reweightor","Use Matrixelements_pp2sqsqbar_nogluino for Matrixelement Reweighting.");
		return new Matrixelements_pp2sqsqbar_nogluino();
	}
	// if(procName == "pp2ttbar"){
	// 	Global::print("Reweightor","Use Matrixelements_pp2ttbar for Matrixelement Reweighting.");
	// 	return new Matrixelements_pp2ttbar();
	// }
	// if(procName == "pp2ttbar2wbwb"){
	// 	Global::print("Reweightor","Use Matrixelements_pp2ttbar2wbwb for Matrixelement Reweighting.");
	// 	return new Matrixelements_pp2ttbar2wbwb();
	// }
	// if(procName == "pp2z2mupmum"){
	// 	Global::print("Reweightor","Use Matrixelements_pp2z2mupmum for Matrixelement Reweighting.");
	// 	return new Matrixelements_pp2z2mupmum();
	// }
	// if(procName == "pp2zp2mupmum"){
	// 	Global::print("Reweightor","Use Matrixelements_pp2zp2mupmum for Matrixelement Reweighting.");
	// 	return new Matrixelements_pp2zp2mupmum();
	// }

	Global::abort("Reweightor","Unknown process for matrix element reweighting.");

	return 0;
}